[package]
build  ="build.rs"
edition="2021"
name   ="weaver"
version="0.1.0"

[dependencies]
blas          ="0.22.0"
derive_builder="0.20.2"
lapack        ="0.19.0"
ndarray       ="0.16.1"
openblas-src  ="0.10.9"
rayon         ="1.10.0"
